Algoritmo "areaQuadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Cintia
// Descrição    : Calcula a area do quadrado
// Autor(a)     : Gabriela Ripoli
// Data atual   : 25/05/2021
Var
//lado variavel de entrada
// area variavel de processamento e saida
lado,area : real

Inicio

//entrada
escreval("Digite o lado do quadrado: ")
leia (lado)


//processamento
area <- lado*lado

//saida
escreval ("A Area do quadrado e:" ,area)

Fimalgoritmo